database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "pushword"
  db_name: "pushpost"
  schema: "pushpost"

server:
  address: "localhost"
  port: 8080

fiber:
  app_name: "PushPost"