database:
  host: "localhost"
  port: 5438
  user: "postgres"
  password: "12345"
  db_name: "postgres"
  schema: "public"

server:
  address: "localhost"

fiber:
  app_name: "PushPost"
  host: "localhost"
  port: 8080


jwt_secret: "pushpost"