services:
  - name: user_service
    base_url: ${USER_SERVICE_URL}
    prefix: /api/user
    health_check:
      path: /health
      interval: 30s
      timeout: 5s
      success_threshold: 2
      failure_threshold: 3
    timeout: 10s
    retry:
      attempts: 3
      delay: 1s

  - name: notification_service
    base_url: ${NOTIFICATION_SERVICE_URL}
    prefix: /api/notification
    health_check:
      path: /api/health
      interval: 30s
      timeout: 5s
      success_threshold: 2
      failure_threshold: 3
    timeout: 10s
    retry:
      attempts: 3
      delay: 1s

  - name: post_service
    base_url: ${POST_SERVICE_URL}
    prefix: /api/post
    health_check:
      path: /api/health
      interval: 30s
      timeout: 5s
      success_threshold: 2
      failure_threshold: 3
    timeout: 10s
    retry:
      attempts: 3
      delay: 1s

